git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never
  branchLogCmd: "git logg {{branchName}} --"
gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  showBottomLine: false
  nerdFontsVersion: "3"
os:
  editPreset: 'nvim'
